//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MI_HOPAC.MiHomeacupService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DoctoresModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DoctoresModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int m_PkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string m_NombreField;
        
        private int m_CedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string m_UbicacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string m_TipoDeMedicinaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int m_Pk {
            get {
                return this.m_PkField;
            }
            set {
                if ((this.m_PkField.Equals(value) != true)) {
                    this.m_PkField = value;
                    this.RaisePropertyChanged("m_Pk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string m_Nombre {
            get {
                return this.m_NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.m_NombreField, value) != true)) {
                    this.m_NombreField = value;
                    this.RaisePropertyChanged("m_Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int m_Cedula {
            get {
                return this.m_CedulaField;
            }
            set {
                if ((this.m_CedulaField.Equals(value) != true)) {
                    this.m_CedulaField = value;
                    this.RaisePropertyChanged("m_Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string m_Ubicacion {
            get {
                return this.m_UbicacionField;
            }
            set {
                if ((object.ReferenceEquals(this.m_UbicacionField, value) != true)) {
                    this.m_UbicacionField = value;
                    this.RaisePropertyChanged("m_Ubicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string m_TipoDeMedicina {
            get {
                return this.m_TipoDeMedicinaField;
            }
            set {
                if ((object.ReferenceEquals(this.m_TipoDeMedicinaField, value) != true)) {
                    this.m_TipoDeMedicinaField = value;
                    this.RaisePropertyChanged("m_TipoDeMedicina");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MiHomeacupService.MainWebServiceSoap")]
    public interface MainWebServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        MI_HOPAC.MiHomeacupService.HelloWorldResponse HelloWorld(MI_HOPAC.MiHomeacupService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<MI_HOPAC.MiHomeacupService.HelloWorldResponse> HelloWorldAsync(MI_HOPAC.MiHomeacupService.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento getDoctoresResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDoctores", ReplyAction="*")]
        MI_HOPAC.MiHomeacupService.getDoctoresResponse getDoctores(MI_HOPAC.MiHomeacupService.getDoctoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDoctores", ReplyAction="*")]
        System.Threading.Tasks.Task<MI_HOPAC.MiHomeacupService.getDoctoresResponse> getDoctoresAsync(MI_HOPAC.MiHomeacupService.getDoctoresRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public MI_HOPAC.MiHomeacupService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(MI_HOPAC.MiHomeacupService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public MI_HOPAC.MiHomeacupService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(MI_HOPAC.MiHomeacupService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDoctoresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDoctores", Namespace="http://tempuri.org/", Order=0)]
        public MI_HOPAC.MiHomeacupService.getDoctoresRequestBody Body;
        
        public getDoctoresRequest() {
        }
        
        public getDoctoresRequest(MI_HOPAC.MiHomeacupService.getDoctoresRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getDoctoresRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int pk;
        
        public getDoctoresRequestBody() {
        }
        
        public getDoctoresRequestBody(int pk) {
            this.pk = pk;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDoctoresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDoctoresResponse", Namespace="http://tempuri.org/", Order=0)]
        public MI_HOPAC.MiHomeacupService.getDoctoresResponseBody Body;
        
        public getDoctoresResponse() {
        }
        
        public getDoctoresResponse(MI_HOPAC.MiHomeacupService.getDoctoresResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getDoctoresResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MI_HOPAC.MiHomeacupService.DoctoresModel[] getDoctoresResult;
        
        public getDoctoresResponseBody() {
        }
        
        public getDoctoresResponseBody(MI_HOPAC.MiHomeacupService.DoctoresModel[] getDoctoresResult) {
            this.getDoctoresResult = getDoctoresResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MainWebServiceSoapChannel : MI_HOPAC.MiHomeacupService.MainWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MainWebServiceSoapClient : System.ServiceModel.ClientBase<MI_HOPAC.MiHomeacupService.MainWebServiceSoap>, MI_HOPAC.MiHomeacupService.MainWebServiceSoap {
        
        public MainWebServiceSoapClient() {
        }
        
        public MainWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MainWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MainWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MainWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MI_HOPAC.MiHomeacupService.HelloWorldResponse MI_HOPAC.MiHomeacupService.MainWebServiceSoap.HelloWorld(MI_HOPAC.MiHomeacupService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            MI_HOPAC.MiHomeacupService.HelloWorldRequest inValue = new MI_HOPAC.MiHomeacupService.HelloWorldRequest();
            inValue.Body = new MI_HOPAC.MiHomeacupService.HelloWorldRequestBody();
            MI_HOPAC.MiHomeacupService.HelloWorldResponse retVal = ((MI_HOPAC.MiHomeacupService.MainWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MI_HOPAC.MiHomeacupService.HelloWorldResponse> MI_HOPAC.MiHomeacupService.MainWebServiceSoap.HelloWorldAsync(MI_HOPAC.MiHomeacupService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<MI_HOPAC.MiHomeacupService.HelloWorldResponse> HelloWorldAsync() {
            MI_HOPAC.MiHomeacupService.HelloWorldRequest inValue = new MI_HOPAC.MiHomeacupService.HelloWorldRequest();
            inValue.Body = new MI_HOPAC.MiHomeacupService.HelloWorldRequestBody();
            return ((MI_HOPAC.MiHomeacupService.MainWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MI_HOPAC.MiHomeacupService.getDoctoresResponse MI_HOPAC.MiHomeacupService.MainWebServiceSoap.getDoctores(MI_HOPAC.MiHomeacupService.getDoctoresRequest request) {
            return base.Channel.getDoctores(request);
        }
        
        public MI_HOPAC.MiHomeacupService.DoctoresModel[] getDoctores(int pk) {
            MI_HOPAC.MiHomeacupService.getDoctoresRequest inValue = new MI_HOPAC.MiHomeacupService.getDoctoresRequest();
            inValue.Body = new MI_HOPAC.MiHomeacupService.getDoctoresRequestBody();
            inValue.Body.pk = pk;
            MI_HOPAC.MiHomeacupService.getDoctoresResponse retVal = ((MI_HOPAC.MiHomeacupService.MainWebServiceSoap)(this)).getDoctores(inValue);
            return retVal.Body.getDoctoresResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MI_HOPAC.MiHomeacupService.getDoctoresResponse> MI_HOPAC.MiHomeacupService.MainWebServiceSoap.getDoctoresAsync(MI_HOPAC.MiHomeacupService.getDoctoresRequest request) {
            return base.Channel.getDoctoresAsync(request);
        }
        
        public System.Threading.Tasks.Task<MI_HOPAC.MiHomeacupService.getDoctoresResponse> getDoctoresAsync(int pk) {
            MI_HOPAC.MiHomeacupService.getDoctoresRequest inValue = new MI_HOPAC.MiHomeacupService.getDoctoresRequest();
            inValue.Body = new MI_HOPAC.MiHomeacupService.getDoctoresRequestBody();
            inValue.Body.pk = pk;
            return ((MI_HOPAC.MiHomeacupService.MainWebServiceSoap)(this)).getDoctoresAsync(inValue);
        }
    }
}
